#!/bin/bash
# This entire script was generated by Bing AI. Can't wait to see if it works.
# The only non-AI parts are for directory management, marked with ## 
# Prompt: 
# Write a bash script to build Apache Airflow from source on WSL2.



# Install prerequisites
sudo apt update
sudo apt install -y python3 python3-pip python3-venv build-essential libssl-dev libffi-dev

pushd ~    ## 
# Create a virtual environment
python3 -m venv airflow-env
source airflow-env/bin/activate

# Upgrade pip and setuptools
pip install --upgrade pip setuptools

# Clone the Airflow repository
git clone https://github.com/apache/airflow.git
pushd airflow ##

# Install Airflow with extras
pip install -e ".[all]"

# Initialize the database
airflow db init

# Create a user
airflow users create \
    --username admin \
    --firstname Admin \
    --lastname User \
    --role Admin \
    --email admin@example.com \
    --password admin

# Start the web server and the scheduler in the background
airflow webserver -D
airflow scheduler -D

popd ## 
popd ## 

# Open the web UI in the default browser
wslview http://localhost:8080
