# BUILD RUST
# Adapting the Amazon Linux version to Ubuntu.
# The adaptations are completely untested on Amazon Linux.
# Original on Amazon Linux based on a script Generated by Bing AI. This ran
# for a while but ended with:
#     Finished dev [unoptimized] target(s) in 1m 43s
#     warning: you have not made a `config.toml`
#     help: consider running `./x.py setup` or copying `config.example.toml` by running `cp config.example.toml config.toml`
#     thread 'main' panicked at '
#
#     couldn't find required command: "c++"
#
#     ', sanity.rs:59:13
#     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#     Build completed unsuccessfully in 0:02:25

source ~/scripts/util/detect-installer.sh
echo "Linux distribution: $BVT_DISTRO"
echo "Selected installer: $BVT_INSTALLER"
if [[ -z "${BVT_INSTALLER}" ]]; then
  echo "BVT_INSTALLER must be set to begin build."
  exit 255
fi
echo "***** BEGIN RUST BUILD SCRIPT $(date) *****"


sudo ${BVT_INSTALLER} update -y
sudo ${BVT_INSTALLER} install -y gcc openssl-devel libcurl-devel
#build-essential = needed to fix error: linker `cc` not found
sudo ${BVT_INSTALLER} install -y build-essential

curl https://sh.rustup.rs -sSf | sh -s -- -y
source $HOME/.cargo/env
rustup component add rust-src
git clone https://github.com/rust-lang/rust.git
cd rust
if [[ "${BVT_DISTRO}" == 'ubuntu' ]]; then
  # Just a guess -- is there an ubuntu-specific value here?
  TARGET=x86_64-unknown-linux-gnu
else
  TARGET=x86_64-unknown-linux-gnu
  fi
if [[ -z "${TARGET}" ]]; then
  echo "TARGET was not set correctly. Terminating."
  exit 255
fi
echo "Build target is ${TARGET}"
./x.py build --stage 1 --target=${TARGET}


