# BUILD RUST
# Generated by Bing AI. This ran for a while but ended with: 
#     Finished dev [unoptimized] target(s) in 1m 43s
#     warning: you have not made a `config.toml`
#     help: consider running `./x.py setup` or copying `config.example.toml` by running `cp config.example.toml config.toml`
#     thread 'main' panicked at '
#     
#     couldn't find required command: "c++"
#     
#     ', sanity.rs:59:13
#     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#     Build completed unsuccessfully in 0:02:25


sudo yum update -y
sudo yum install -y gcc openssl-devel libcurl-devel
curl https://sh.rustup.rs -sSf | sh -s -- -y
source $HOME/.cargo/env
rustup component add rust-src
git clone https://github.com/rust-lang/rust.git
cd rust
./x.py build --stage 1 --target=x86_64-unknown-linux-gnu

